package shared.io.jsonParse.traits

import shared.com.ortb.model.attributes.ApiPaginationResponseAttributesModel

trait ApiPaginationResponseAttributesModelCustomJsonEncoder
  extends BasicJsonEncoder[ApiPaginationResponseAttributesModel]
