package shared.com.ortb.adapters

import shared.com.ortb.adapters.traits.implementations.EntityWrapperAdapterImplementation

class EntityWrapperAdapterConcreteImplementation extends EntityWrapperAdapterImplementation
