package shared.com.ortb.adapters.implementations

import shared.com.ortb.adapters.traits.implementations.EntityWrapperAdapterImplementation

class EntityWrapperAdapterConcreteImplementation extends EntityWrapperAdapterImplementation
