package shared.com.ortb.adapters.implementations

import shared.com.ortb.adapters.traits.implementations.RepositoryOperationResultModelAdapterImplementation

class RepositoryOperationResultModelAdapterConcreteImplementation extends RepositoryOperationResultModelAdapterImplementation
